name: Codestyle

on: [pull_request]

env:
  OPEN_UCX_LINK: https://github.com/openucx/ucx
  OPEN_UCX_BRANCH: v1.9.x
jobs:
  check-commit-title:
    runs-on: ubuntu-latest
    name: Check commit title
    steps:
    - uses: actions/checkout@v1
    - name: Check commit title
      run: |
        set -eE
        range="origin/$GITHUB_BASE_REF..HEAD"
        ok=1
        for sha1 in `git log $range --format="%h"`
        do
          title=`git log -1 --format="%s" $sha1`
          if echo $title | grep -qP '^Merge |^[0-9A-Z/_\-]*: \w'
          then
            echo "Good commit title: '$title'"
          else
            echo "Bad commit title: '$title'"
            ok=0
          fi
        done
        if [ $ok -ne 1 ]
        then
          exit 1
        fi
